# Generated by Django 4.1.6 on 2023-03-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('user', '0001_initial'),
        ('course', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parentId',
            field=models.ManyToManyField(blank=True, related_name='parents', to='user.parent'),
        ),
        migrations.AddField(
            model_name='mark',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='mark',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
