# Generated by Django 4.1.6 on 2023-03-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('academicYear', models.CharField(max_length=4)),
                ('courseName', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
                ('courseLanguage', models.CharField(max_length=30)),
            ],
        ),
    ]
