# Generated by Django 4.1.5 on 2023-03-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('calendarId', models.AutoField(primary_key=True, serialize=False)),
                ('academicYear', models.IntegerField()),
                ('startDate', models.DateField()),
                ('numWorkDays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=20)),
                ('Date', models.DateField()),
                ('holiday', models.BooleanField(default=False)),
                ('calendarId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='days',
            field=models.ManyToManyField(blank=True, to='calendars.day'),
        ),
    ]
