# Generated by Django 4.1.6 on 2023-03-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_day_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='calendars.day'),
        ),
    ]
