# Generated by Django 4.1.6 on 2023-03-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
