# Generated by Django 4.1.6 on 2023-03-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_newsletter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
